global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# No scrape_configs needed since we're using remote-write only
# No remote_write/remote_read config needed - Prometheus will accept writes to /api/v1/write by default 